# Generated by Django 4.0.4 on 2023-03-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinfo',
            name='category',
        ),
    ]
