# Generated by Django 4.0.4 on 2023-03-09 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=255)),
                ('img_src', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('pub_date', models.TextField()),
                ('expert', models.TextField(default='')),
                ('category', models.TextField(blank=True, default='', null=True)),
                ('sourcename', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
