# Generated by Django 4.0.4 on 2023-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfeedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='userpass',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
