# Generated by Django 4.0.4 on 2023-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_userpass_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedinfo',
            name='url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
