# Generated by Django 4.0.4 on 2023-03-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='expert',
            field=models.TextField(default=''),
        ),
    ]
