# Generated by Django 4.0.4 on 2023-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_reader', '0003_alter_feedinfo_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinfo',
            name='category',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
