# Generated by Django 4.0.4 on 2023-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_reader', '0004_alter_feedinfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.TextField(blank=True, default='', null=True)),
                ('tag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='sourcename',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
